export const departamentosColombia = [
  { id: 0, name: "selecciona una opcion", value: "0" },
  { id: 1, name: "Amazonas", value: "AM" },
  { id: 2, name: "Antioquia", value: "ANT" },
  { id: 3, name: "Arauca", value: "ARA" },
  { id: 4, name: "Atlántico", value: "ATL" },
  { id: 5, name: "Bolívar", value: "BOL" },
  { id: 6, name: "Boyacá", value: "BOY" },
  { id: 7, name: "Caldas", value: "CAL" },
  { id: 8, name: "Caquetá", value: "CAQ" },
  { id: 9, name: "Casanare", value: "CAS" },
  { id: 10, name: "Cauca", value: "CAU" },
  { id: 11, name: "Cesar", value: "CES" },
  { id: 12, name: "Chocó", value: "CHO" },
  { id: 13, name: "Córdoba", value: "COR" },
  { id: 14, name: "Cundinamarca", value: "CUN" },
  { id: 15, name: "Guainía", value: "GUA" },
  { id: 16, name: "Guaviare", value: "GUV" },
  { id: 17, name: "Huila", value: "HUI" },
  { id: 18, name: "La Guajira", value: "LAG" },
  { id: 19, name: "Magdalena", value: "MAG" },
  { id: 20, name: "Meta", value: "MET" },
  { id: 21, name: "Nariño", value: "NAR" },
  { id: 22, name: "Norte de Santander", value: "NSA" },
  { id: 23, name: "Putumayo", value: "PUT" },
  { id: 24, name: "Quindío", value: "QUI" },
  { id: 25, name: "Risaralda", value: "RIS" },
  { id: 26, name: "San Andrés y Providencia", value: "SAP" },
  { id: 27, name: "Santander", value: "SAN" },
  { id: 28, name: "Sucre", value: "SUC" },
  { id: 29, name: "Tolima", value: "TOL" },
  { id: 30, name: "Valle del Cauca", value: "VAC" },
  { id: 31, name: "Vaupés", value: "VAU" },
  { id: 32, name: "Vichada", value: "VID" },
];
